"""first_db_creation

Revision ID: cf2d92f45c9d
Revises: 
Create Date: 2026-03-20 11:58:12.313507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2d92f45c9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdr_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_versione', sa.String(length=100), nullable=False),
    sa.Column('inizio_validita', sa.Date(), nullable=False),
    sa.Column('fine_validita', sa.Date(), nullable=False),
    sa.Column('dati', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdr_versions_fine_validita'), 'cdr_versions', ['fine_validita'], unique=False)
    op.create_index(op.f('ix_cdr_versions_inizio_validita'), 'cdr_versions', ['inizio_validita'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('operazione_id', sa.String(), nullable=True),
    sa.Column('voto', sa.String(), nullable=True),
    sa.Column('commento', sa.Text(), nullable=True),
    sa.Column('param', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('created_at_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('utenti',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_email'), 'utenti', ['email'], unique=True)
    op.create_index(op.f('ix_utenti_id'), 'utenti', ['id'], unique=False)
    op.create_index(op.f('ix_utenti_username'), 'utenti', ['username'], unique=True)
    op.create_table('operazioni',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('param', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operazioni_id'), 'operazioni', ['id'], unique=False)
    op.create_index(op.f('ix_operazioni_param'), 'operazioni', ['param'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operazioni_param'), table_name='operazioni')
    op.drop_index(op.f('ix_operazioni_id'), table_name='operazioni')
    op.drop_table('operazioni')
    op.drop_index(op.f('ix_utenti_username'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_id'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_email'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_cdr_versions_inizio_validita'), table_name='cdr_versions')
    op.drop_index(op.f('ix_cdr_versions_fine_validita'), table_name='cdr_versions')
    op.drop_table('cdr_versions')
    # ### end Alembic commands ###
